apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
  'backstage.io/kubernetes-label-selector': 'app=my-kubernetes-component'
spec:
  lifecycle: production
  owner: my-team
  type: service
